name: architectenbureau stijn janssens
favicon: null
layout_spectrum: 0.26068
typography_spectrum: 0.56319
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cbcbcb'
    - '#939393'
    - '#aeaeae'
    - '#eee8db'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
